server:
  port: 8080

spring:
  application:
    name: mercadona

  datasource:
    url: jdbc:postgresql://localhost:5432/mercadona
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update